project:
  type: website

website:
  google-analytics: G-3T34S31LG1
  sidebar:
    style: docked
    title: "Stat 2"
    logo: assets/stat_bear.png
    contents:
      - href: index.qmd
        text: Home 
      - href: staff.qmd
        text: Staff
      - href: syllabus.qmd
        text: Syllabus
      - href: license.qmd
        text: License
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



